POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "a!12345678"
}

###

GET http://localhost:8080/print_hash HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2NzA4OTcwfQ.ZftMaHS2-4HBv5XVsvM-9AN5rstAr25dK3t3u-NMsEA

###

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "a!12345678"
}

###

GET http://localhost:8080/game HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2ODE0MTc5fQ.waj8EJiNv19uWvsfzzZ8BPd0b0_LqiQINZaxBKrsmog

###

POST http://localhost:8080/game HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2Nzk5NDYzfQ.HzXphD5tM3wWfX6nBEWwRV8yJOOcDVFyqll6Frwhax4
Content-Type: application/json

{
    "userId": 2,
    "characterName": "Buddy Holly",
    "gameNumber": 2
}

###
GET http://localhost:8080/game/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2Nzk4OTcxfQ.HFTX932lhMRPK14ZLWXwuSWJqHySUxzqt-Dr6BbWp2Q

###
PUT http://localhost:8080/game HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2Nzk4OTcxfQ.HFTX932lhMRPK14ZLWXwuSWJqHySUxzqt-Dr6BbWp2Q
Content-Type: application/json

{
    "userId": 2,
    "characterName": "Ocean Man",
    "gameNumber": 1
}

###
DELETE http://localhost:8080/game HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2Nzk5NDYzfQ.HzXphD5tM3wWfX6nBEWwRV8yJOOcDVFyqll6Frwhax4
Content-Type: application/json

{
    "userId": 2,
    "characterName": "Buddy Holly",
    "gameNumber": 2
}

###

POST http://localhost:8080/inventory HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2ODE0MTc5fQ.waj8EJiNv19uWvsfzzZ8BPd0b0_LqiQINZaxBKrsmog
Content-Type: application/json

{
    "gameId": 2,
    "resourceId": 1,
    "quantity": 2
}

###

GET http://localhost:8080/resources/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqYWlsYnJlYWsiLCJzdWIiOiJ1c2VyIiwidXNlcl9pZCI6Miwicm9sZV9pZCI6MiwiZXhwIjoxNjY2ODM1MDc0fQ.XaaEXiomct7MgVx2TZx__hWbLgxbvDEdAAe_v_o_2SU